from pydantic import BaseModel
from typing import Literal, Optional, Dict, Any, List


class TaskInput(BaseModel):
    """Data sent by the frontend when a user creates a task."""
    task_id: Optional[str] = None  # Generated by backend on submit
    modality: Literal["text", "image", "file"]
    content: str  # Raw text or data/-relative file path
    context: Dict[str, Any] = {}  # Optional metadata, e.g. {"unit": "Unit-2"}
    model_override: Optional[str] = "auto"  # "auto" or a model name like "deepseek-r1"


class TraceEvent(BaseModel):
    """Streamed live from backend to frontend over WebSocket as the AI agent works."""
    task_id: str
    step: Literal[
        "manager", "classify", "plan", "tool_call", "verify_pass",
        "verify_fail", "retry", "generate", "done", "error",
        "stream_chunk", "self_heal"
    ]
    payload: Dict[str, Any]
    timestamp: str  # ISO 8601 string format


class ArtifactRef(BaseModel):
    """Reference to a file generated by the system (Word/Excel/PPT)."""
    type: Literal["docx", "xlsx", "pptx", "py", "txt", "md", "code"]
    filename: str
    path: str  # Relative path inside data/ or outputs/


class TaskResult(BaseModel):
    """Final result returned when a task finishes execution."""
    task_id: str
    status: Literal["queued", "running", "done", "error"]
    artifacts: List[ArtifactRef] = []
    summary: str = ""
    error: Optional[str] = None