# Generated by Setu AI — Task: 37e6942f-3d21-43e9-9f9d-841eb0f853f7
# WARNING: NEEDS HUMAN REVIEW

"""Data Processing Utility for Industrial Sensor Logs."""

def process_sensor_data(readings: list[dict]) -> dict:
    """Process sensor readings and return statistics."""
    if not readings:
        return {"error": "No readings provided"}
    values = [r.get("value", 0.0) for r in readings]
    avg = sum(values) / len(values)
    return {
        "count": len(values),
        "average": round(avg, 4),
        "min": min(values),
        "max": max(values),
        "variance": round(sum((v - avg) ** 2 for v in values) / len(values), 4),
        "range": max(values) - min(values),
    }

if __name__ == "__main__":
    sample = [{"sensor": "T-101", "value": v} for v in [72.3, 73.1, 71.8, 72.9]]
    print(f"Statistics: {process_sensor_data(sample)}")
