# Generated by Setu AI — Task: test-codegen-001
# Test log: All tests passed!

"""Modbus TCP Polling Script for Industrial Sensor Readings."""
import struct
import socket
import time

def read_holding_registers(host: str, port: int, unit_id: int,
                           start_addr: int, count: int) -> list[int]:
    """Read holding registers from a Modbus TCP device."""
    transaction_id = 1
    protocol_id = 0
    length = 6
    function_code = 3  # Read Holding Registers

    header = struct.pack('>HHHBBHH',
        transaction_id, protocol_id, length,
        unit_id, function_code, start_addr, count)

    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.settimeout(5.0)
        sock.connect((host, port))
        sock.send(header)
        response = sock.recv(256)

    byte_count = response[8]
    values = []
    for i in range(0, byte_count, 2):
        val = struct.unpack('>H', response[9+i:11+i])[0]
        values.append(val)
    return values

def poll_sensors(host="127.0.0.1", port=502, interval=2.0, num_reads=5):
    """Poll sensor registers at a fixed interval."""
    results = []
    for i in range(num_reads):
        values = read_holding_registers(host, port, unit_id=1,
                                         start_addr=0, count=4)
        results.append({"reading": i+1, "values": values,
                        "timestamp": time.time()})
        if i < num_reads - 1:
            time.sleep(interval)
    return results

if __name__ == "__main__":
    data = poll_sensors()
    for entry in data:
        print(f"Reading {entry['reading']}: {entry['values']}")
